spring.profiles: consumer

spring.rabbitmq.host: rabbit

rabbit:
  jobs:
    exchange: jobs_exchange
    routingKey: job_producer
    queue: jobs_queue
  results:
    routingKey: result_producer

spring:
  rabbitmq:
    listener:
      simple:
        prefetch: 1
