version: "3.1"

services:

  rabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:15672"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  java-consumer:
    build:
      dockerfile: dev.Dockerfile
      context: ./java/worker
    # volumes:
    #   - maven-repository:/root/.m2
    environment: 
      - SPRING_PROFILES_ACTIVE=consumer
    depends_on:
      - rabbit
      
  java-producer:
    build:
      dockerfile: dev.Dockerfile
      context: ./java/worker
    # volumes:
    #   - maven-repository:/root/.m2
    environment: 
      - SPRING_PROFILES_ACTIVE=producer
    depends_on:
      - rabbit

  wshost:
    build:
      dockerfile: Dockerfile
      context: ./nodejs/backend
    ports:
      - 8090:8080
    environment:
      - TARGET_QUEUE=jobs_queue
      - RESULT_ROUTING_KEY=result_producer
      - RABBIT_HOST=rabbit
    depends_on:
      - rabbit
      
  monitor:
    build:
      dockerfile: Dockerfile
      context: ./nodejs/frontend
      # args:
      #   WS_HOST: wshost:8080
    ports:
      - 8080:80
    depends_on:
      - wshost
    volumes:
      - ./nodejs/frontend:/usr/share/nginx/html
      
# still not working
# volumes:
#   maven-repository: