version: "3.1"

services:

  rabbit:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  java-consumer:
    build:
      dockerfile: Dockerfile
      context: ./java/worker
#   volumes:
#     - maven-repository:/root/.m2
    environment: 
      - SPRING_PROFILES_ACTIVE=consumer
    depends_on:
      - rabbit
      
  java-producer:
    build:
      dockerfile: Dockerfile
      context: ./java/worker
#   volumes:
#     - maven-repository:/root/.m2
    environment: 
      - SPRING_PROFILES_ACTIVE=producer
    depends_on:
      - rabbit

      
# still not working
# volumes:
#   maven-repository: